name: Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'app-service'
  PROJECT_ID: 'project-15471679-4555-4915-8a1'
  AR_REPO_LOCATION: 'us-central1'
  AR_URL: 'us-central1-docker.pkg.dev/project-15471679-4555-4915-8a1/app-service-registry'
  SERVICE_ACCOUNT: 'github-actions-service-account@project-15471679-4555-4915-8a1.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/885268142795/locations/global/workloadIdentityPools/my-app-wif-pool/providers/github-actions-provider'

jobs:
  push_to_ar:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Build Docker Image
        run: |
          docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" ./order-service

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'MODERATE,HIGH,CRITICAL'
          exit-code: '1'   

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Add tags and push image to Artifact Registry
        run: |
          docker tag "${{ env.IMAGE_NAME }}:${{ github.sha }}" "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"